language: node_js
node_js: '6'
notifications:
  slack:
    secure: T1m1AiydpfF2MonU0x1ZBCUUeF6N3pMmRRxU3QxI9Hs2o9arftBZ7nCnVJUW1MCp4vVzjkdPpSkAs5a2YWlBPLUr3OoC2e5n7rjQP0qvz/CUl/OsGgHA8JA/70CqNiBlqKVRGZlPHkv2fR+IAgIzijf6u9sR8qX3okDcatHD0fwHj3RHlbXF/zqA+u20Ve/aBLb09qidzcpsA3kNsBBOcDAFa0C9MqSXA7S8vR8xY62no0ysUx+yVqOp+H9Xac2PpqJ/x8L5slq4jqAEoBdGfkM/tkdWi7Rzfv0bR/v1xHudiMUEEobY/JXNbpVWo+C3E8MyPEOOced9tdAY+jLOhuQnNoY+8gUT4cqgCshye2QYbgVnmS3tWpHvq7JaQ/rOxC1qS4FX6OtGxbRA0Fm8tmA8FoQDkiuTo0n5GcRigKk/mLxb+zLvaii2z44mhwREBEIF9syD9Rre1ZgwleSpEnF6Zjpo+dNe2te049kYOCvLz/UhAYnNbZ1sZI5D9tCC3Cb7NPsLBX5ZDrTUqzj2uVM0NN9y1dczX3eXxW3DVUfqm2iXW6HmGVGdQ/LOJcSyHl9qkfsgMo62d8PdPCjqgf14JqigQnz/BKWvFkZo3ScS6Wg19Pk7decIcZZGp/gZJ75jMgV6fsY3fBs/DxioHiATyO4pVWi9SSSJ5PnrFxk=
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: aWn+KvoVg4Ik6OKhts9of4H7G145/iME6s/ltG9SkBh70QfJmWzjzVWZs8iB7HryNp2ocekpPK+jWKL2rKcHCUOv+zyeQ4UAsddHm6wukjy+4RJUNW2+wjRfkp5+xwty9auPfh+Mqfvl+/cENXoHjQ5IpV9TshZAy1TZUncJTCKpeDIP2C7xOzI44b/08Ly8Bae3TveYSk8HQdMOFkOgFVwhOMs2L6hSJlLAuXDu3w5J/InB4inPzHfUfgZhsn9B++0bFI2jO1Cdn56YsGcX26cwzEt+cnb2Pivz300mmD6ERYvUAtmVeLMVE3UznJNsetBJ7H+ObV5Bthscwcq2EVmiqQATVCrSqbPpZbn2IIqoJHBKQc3ijH+4bIMGgs/UgRDMQngzRqIiIXW4fCC+bHVlI7zNMAjSpsgieno34Uq92qXGjjb3TGudAkEnyv9v6w6kymN/uJ91Vx1IKNv/X2hXLsjyW9VfVeVjT8vwXLkjWo8rx+lQQtGbipAF3IUeuWEIeoSLq0vEqQyQTyQi7MzEit3V+10gLZOvxFi1DnTm2OAO0dZe+zfI+4SMH4Q5GXEoW35klph4AJDUHkSRoa74QwRhsr91j+L7wKAI4TeXbUD9dnnzLeus2/RgTONSZiiYsI8dGs5areX/bOjSNRQtKZFjgj2IOoxoMiY2XHQ=
  on:
    tags: true
    repo: xogroup/toki-config-file
